zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "49181:2181"
    - "22"
nimbus:
  image: n8hdqc/storm-nimbus:0.10.0
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links: 
    - zookeeper:zk
supervisor:
  image: n8hdqc/storm-supervisor:0.10.0
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: n8hdqc/storm-ui:0.10.0
  ports:
    - "49080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk